base:
  project: winequakity-project
  random_state: 42
  target: TARGET

data_source:
  mongo_db:
    host: localhost
    port: 27017
    db_name: wine_quality_db
    collection_name: wine_quality_collection

load_data:
  raw_dataset_csv: data/raw/winequality.csv

split_data:
  train_path: data/processed/train_winequality.csv
  test_path: data/processed/test_winequality.csv
  test_size: 0.25

model_dir: save_model

estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.7

reports:
  params: report/params.json
  scores: report/scores.json